version: 0.2

#run-as: Linux-user-name

#env:
  #shell: shell-tag
  #variables:
    #key: "value"
    #key: "value"
  #parameter-store:
    #key: "value"
    #key: "value"
  #exported-variables:
    #- variable
    #- variable
  #secrets-manager:
    #key: secret-id:json-key:version-stage:version-id
  #git-credential-helper: no | yes

#proxy:
  #upload-artifacts: no | yes
  #logs: no | yes

#batch:
  #fast-fail: false | true
    # build-list:
    # build-matrix:
    # build-graph:

phases:
  install:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
    runtime-versions:
      nodejs: 18
    commands:
      - npm i -g yarn
      - npm i -g typescript
      - npm i -g @nestjs/cli
#    finally:
#      - command
#      - command
    # steps:
#  pre_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
#    commands:
#      - command
#      - command
#    finally:
#      - command
#      - command
    # steps:
  build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
    commands:
      - yarn
      - yarn build
#    finally:
#      - command
#      - command
    # steps:
  post_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
    commands:
      - yarn test
      - yarn test:e2e
#    finally:
#      - command
#      - command
    # steps:
#reports:
#  report-group-name-or-arn:
#    files:
#      - location
#      - location
#    base-directory: location
#    discard-paths: no | yes
#    file-format: report-format
artifacts:
  files:
    - '**/*'
#  name: artifact-name
#  discard-paths: no | yes
#  base-directory: location
#  exclude-paths: excluded paths
#  enable-symlinks: no | yes
#  s3-prefix: prefix
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      name: secondary-artifact-name
#      discard-paths: no | yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: no | yes
#      base-directory: location
#cache:
#  paths:
#    - path
#    - path
